### ISSUE TITLE
tmuxp issue?

### ISSUE THREAD

**Issue by tony** [bitprophet/dotfiles#5]
Regarding https://twitter.com/bitprophet/status/561356905843392514, do you remember what you were trying to do?

**Comment by bitprophet** [comment]
Not offhand, but it was largely what the mux script does - open new window, split into two tall panes, optionally split the right hand pane again a few more times.

At least one of those calls was not something the tmuxp API seemed to anticipate, and IIRC the core wrapper for the `tmux` command itself wasn't readily reusable (the functions were largeish and I couldn't simply override the bits I needed to tweak).

Probably was one of these, like one of the flags I am using had no analogue in tmuxp's end?

* https://github.com/bitprophet/dotfiles/blob/86f18d28358e6ab7625121dc40e17dc488c06313/bin/mux#L47
* https://github.com/bitprophet/dotfiles/blob/86f18d28358e6ab7625121dc40e17dc488c06313/bin/mux#L61
* https://github.com/bitprophet/dotfiles/blob/86f18d28358e6ab7625121dc40e17dc488c06313/bin/mux#L70

**Comment by tony** [comment]
Sorry for the late response.  I think you already solved your issue, but want to make sure the tmuxp api isn't limiting ability to make commands.

``Session``, ``Window`` and ``Pane`` all have a ``.tmux()`` that can be used to send custom arguments over.

- http://tmuxp.readthedocs.org/en/latest/api.html#tmuxp.util.tmux - Totally generic tmux command object. Would it have been better if that was ``tmux_cmd``?
- http://tmuxp.readthedocs.org/en/latest/api.html#tmuxp.Session.tmux - I just noticed the documentation on this was missing. This would allow you to create ``new-window`` with any arguments you wish. Would this have handled your issue?
- http://tmuxp.readthedocs.org/en/latest/api.html#tmuxp.Window.tmux
- http://tmuxp.readthedocs.org/en/latest/api.html#tmuxp.Pane.tmux

**Comment by tony** [comment]
Think it would have been more intuitive if it was ``session.cmd()``, ``window.cmd()``, ``pane.cmd()`` instead of ``session.tmux()``, ``window.tmux()``, ``pane.tmux()``?

**Comment by bitprophet** [comment]
I really wish I had committed some version of my experiment to git, I truly don't remember the details at this point. It's certainly possible `Session.tmux` may have been something I could've used.

Also, definitely agree that `.cmd` is a bit clearer a name than `.tmux`.

Thanks for the followup, sorry I can't be of more use :)

**Comment by tony** [comment]
As of tmux 0.8, the API was refactored to use ``.cmd``. The subprocess function for tmux commands in now ``tmuxp_cmd``.  Thanks for getting back.  Ultimately I kind of hope to sunset tmuxp and do something in extend it in C or golang sometime.
